spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

app:
  internal:
    api-key: ${INTERNAL_API_KEY:local-secret-key}
  jwt:
    secret: ${APP_JWT_SECRET:your-very-long-and-safe-secret-key-at-least-32-chars}

logging:
  level:
    io.github.speranskyartyom.taxi_microservices: INFO